### ISSUE TITLE
Suggestion: move it to BSD License or make it proprietary

### ISSUE THREAD

**Issue by cheny0y0** [lchzh3473/sim-phi#10]
I've heard that there are lots of low-creative videos on bilibili and you are wanting to make them down. So you can choose BSD License and add more limitation, or make it proprietary(proprietary means it is not free software, not means it is closed-source).

**Comment by FeyXieXzf** [comment]
And that must be the worst solution to the problem - What? Make it proprietary to stop these videos?

**Comment by FeyXieXzf** [comment]
What make you think like such?

**Comment by FeyXieXzf** [comment]
Moving to BSD may sound ok, but closing-source it is definitely not a solution.

**Comment by realtvop** [comment]
有事不在，见信尽快回复～
