### ISSUE TITLE
有关新版本资源加载失败从而无法使用的问题

### ISSUE THREAD

**Issue by huskydog-zy** [lchzh3473/sim-phi#14]
rt
![image](https://github.com/lchzh3473/sim-phi/assets/102460759/3f497b0e-6a1d-4136-b574-42cef44c4849)
打开报错信息发现
![image](https://github.com/lchzh3473/sim-phi/assets/102460759/85a75de7-c554-460d-a7a9-85d15c7f934e)
打开随便一个文件，出现
![image](https://github.com/lchzh3473/sim-phi/assets/102460759/d802a689-6678-4801-b886-e37a565d70c8)
403，无权限
问题出自i3.hdslb.com这个网站
了解后发现这是B站的CDN，将网址前面的i3改为i1👇
https://i0.hdslb.com/bfs/face/a218ece0645ca903d785a5b1ddacbcbb4e21ddaa.png
rt，可正常显示
![image](https://github.com/lchzh3473/sim-phi/assets/102460759/3d4f8272-6bae-4125-b7ff-9b9a65507d8a)
个人推测问题原因：B站服务器变动
建议修改方法：更换图床
感谢作者！

**Comment by huskydog-zy** [comment]
上面写错了，是改成i0，i1也不行

**Comment by lchzh3473** [comment]
i3的问题已解决，建议清除浏览器缓存然后重试；
其它无法访问的问题：该CDN做了简单的防盗链，需要将`referrerPolicy`配置为`no-referrer`方可正常加载。

**Comment by huskydog-zy** [comment]
更换浏览器已解决，感谢作者提供这么棒的播放器！
