### ISSUE TITLE
本地运行不了？

### ISSUE THREAD

**Issue by cbs001** [lchzh3473/sim-phi#17]
![image](https://github.com/user-attachments/assets/3e85c129-69b5-487f-89a6-8e5ebed04f80)

**Comment by lchzh3473** [comment]
参考：[使用 npm 注册表 - GitHub 文档](https://docs.github.com/zh/packages/working-with-a-github-packages-registry/working-with-the-npm-registry)

> 需要访问令牌才能发布、安装和删除专用、内部和公共包。

在终端中运行以下命令登录GitHub：

```bash
npm login --registry=https://npm.pkg.github.com/
```

完成登录后，你的`.npmrc`配置文件应自动添加以下内容：

```ini
# 通过个人访问令牌进行npm与GitHub Packages的认证
//npm.pkg.github.com/:_authToken=YOUR_GITHUB_TOKEN
```

最后再次运行`npm install`。
