### ISSUE TITLE
有关Flick判定的问题

### ISSUE THREAD

**Issue by minecraftfen** [lchzh3473/sim-phi#2]
我在游玩`sim-phi`时发现，似乎只需要移动大于1个像素的距离，就可以判定为滑动(触摸反馈变红)，这导致`sim-phi`中Filck时常可以当作蓝键点击，因为让人手从接触屏幕到离开产生的移动小于1像素比大于1像素还难。

我记得phigros的Flick判定应该比这更复杂一些：

- 目测至少需要移动10-25px的距离才能判定为滑动
- 哪怕小幅度离开判定范围，只要滑动路径与判定区重叠即可判定
- 判定Filck后似乎会重置滑动状态，必须继续滑动一段距离才能判定下一个Filck

**Comment by minecraftfen** [comment]
# 解决方案建议1

## 滑动距离问题

我觉得应该可以在网页中放一个一个隐藏的SVG,每产生一个触控移动事件就把坐标加入SVG的Path数据中，然后用Path标签内建的求长度方法获取移动距离

实例(未调试，仅会意)：
```html
<svg id="filckbox"> <!-- 注意让这个的尺寸和触屏区域一样大 -->
    <path d="坐标列表" id="flick1">
    <path d="坐标列表" id="filck2">
    ...
</svg>
<script>
flickbox=document.getElementById("flickbox");
function pointerdown(e){
    obj=document.createElementNS("http://www.w3.org/2000/svg","path");
    obj.d="M "+e.x+","+e.y; // "M x,y"，表示提笔移动到点击位置，开头末尾无空格
    e.target.obj=obj; // 别照着这个做，绝对行不通，不能多押
};
function pointermove(e){
    e.target.obj.d+="L "+e.x+","+e.y; // "L x,y"，表示落移动到移动位置，开头末尾无空格
    if(e.target.obj.getTotalLength()>=25){ // 获取路径长度
        flag_flick=true // 触发flick判定
    }
}
function pointerup(e){
    flickbox.removeChild(e.target.obj)
}
</script>
```

**Comment by minecraftfen** [comment]
不过上面这个方法可能时空间复杂度相对求直线距离要大一些，我也不知道Phigros是求直线距离还是移动曲线长度的

**Comment by minecraftfen** [comment]
滑动范围应该可以用计算几何相交的方式实现(虽然我也不知道怎么实现hhh)
滑动重置的话，应该有一个flag就行，就像我上面提到的`flag_flick`，判定后把它重新放倒就可以了

**Comment by lchzh3473** [comment]
我会考虑多种Flick判定方案，在后续版本同时进行测试：
- 位移：连续触摸点位移一段距离更新判定(当前实现的方法)；
- 速度：计算速度(大小或方向)改变一定值更新判定(也许是Phigros的方法)；
- 角位移：连续触摸点夹角超过一定值更新判定(另一种可行的方法)。
> 概念：同一触摸点连续位移时两次更新判定之间仅能判定一个Flick

**Comment by lchzh3473** [comment]
结果方案：实时计算速度并指定触发/更新单个Flick的速度（对于不同物理尺寸的设备可能存在手感差异，但应该问题不大）
