### ISSUE TITLE
有做SEO优化吗

### ISSUE THREAD

**Issue by minecraftfen** [lchzh3473/sim-phi#3]
如果不想有低质量视频的话，应该设置成在搜索引擎中找不到才是
但是我在`<head>`里找不到SEO(搜索引擎优化)相关的`<meta>`标签诶
而且网站根目录也没有限制爬虫访问的robot.txt文件

**Comment by lchzh3473** [comment]
目前GitHub似乎会屏蔽国内搜索引擎的爬虫，暂时不设置爬虫协议
