### ISSUE TITLE
Safari12无法使用模拟器

### ISSUE THREAD

**Issue by Caixuxukun** [lchzh3473/sim-phi#6]
在Safari12点模拟器的任何链接和按钮都没有反应，
在`script.js`第181行代码后面插入下面的代码至少可以解决这个问题（否则为什么用不了模拟器都不知道）。
```
if (parseFloat(info.version) < 13) {
	const style = document.createElement('style');
	style.innerHTML = `
	.fade {
		z-index: -1 !important;
	}
	#view-content {
		overflow: auto;
		-webkit-overflow-scrolling: touch;
	}`
	document.head.appendChild(style);
}
```
但是读取文件还是会报错
![IMG_3593](https://user-images.githubusercontent.com/90492691/188109404-8b5a90a1-0772-4afb-8bc3-da77db6acbbd.PNG)

**Comment by lchzh3473** [comment]
将在lchzh本人得到相关设备之后进行实测并适配

**Comment by lchzh3473** [comment]
已确认图中所述问题发生于Safari12，`webkitAudioContext`接口的`decodeAudioData()`方法仅支持回调函数语法，因此会缺少一个成功回调的参数。

已经得到相关设备并进行了兼容 https://github.com/lchzh3473/sim-phi/commit/0d08d260d7fb66590cd888f1a46f708bf96ba454
